version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
    container_name: node-server
    ports:
      - "8080:8080"
    volumes:
      - "./server:/app/src"
    command: "npx nodemon src/server.js"

  mysql:
    image: mysql:5.7.31
    container_name: assignment
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
